name: cars_simulation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter  
  flutter_svg: ^2.1.0
  collection: ^1.19.0
  zoom_widget: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/car.svg
    - assets/gas_station.svg
